# /////////////////////////////////////////
# <-*-*-----*-*-*- Actions-*-*-*-----*-*->
# /////////////////////////////////////////

standard = Action.find_or_create_by!(name: "Standard Action")
full_round = Action.find_or_create_by!(name: "Full-Round Action")
move = Action.find_or_create_by!(name: "Move Action")
swift = Action.find_or_create_by!(name: "Swift Action")
free = Action.find_or_create_by!(name: "Free Action")
immediate = Action.find_or_create_by!(name: "Immediate Action")
ten = Action.find_or_create_by!(name: "Ten Minutes")
one_minute = Action.find_or_create_by!(name: "One Minute")
three_rounds = Action.find_or_create_by!(name: "Three Rounds")
varies = Action.find_or_create_by!(name: "See Text")
thirty_minutes = Action.find_or_create_by!(name: "Thirty Minutes")

# /////////////////////////////////////////
# <-*-*-----*-*-*- Sources-*-*-*-----*-*->
# /////////////////////////////////////////

core_rulebook = Source.find_by!(title: "Core Rulebook", abbreviation: "CR", code: "PZO1110")
bestiary_1 = Source.find_by!(title: "Bestiary 1", abbreviation: "B1", code: "PZO1112")
advanced_players_guide = Source.find_by!(title: "Advanced Player's Guide", abbreviation: "APG", code: "PZO1115")
bestiary_2 = Source.find_by!(title: "Bestiary 2", abbreviation: "B2", code: "PZO1116")
ultimate_magic = Source.find_by!(title: "Ultimate Magic", abbreviation: "UM", code: "PZO1117")
ultimate_combat = Source.find_by!(title: "Ultimate Combat", abbreviation: "UC", code: "PZO1118")
bestiary_3 = Source.find_by!(title: "Bestiary 3", abbreviation: "B3", code: "PZO1120")
advanced_race_guide = Source.find_by!(title: "Advanced Race Guide", abbreviation: "ARG", code: "PZO1121")
bestiary_4 = Source.find_by!(title: "Bestiary 4", abbreviation: "B4", code: "PZO1127")
advanced_class_guide = Source.find_by!(title: "Advanced Class Guide", abbreviation: "ACG", code: "PZO1129")
bestiary_5 = Source.find_by!(title: "Bestiary 5", abbreviation: "B5", code: "PZO1133")
ultimate_intrigue = Source.find_by!(title: "Ultimate Intrigue", abbreviation: "UI", code: "PZO1134")
ultimate_wilderness = Source.find_by!(title: "Ultimate Wilderness", abbreviation: "UW", code: "PZO1140")
planar_adventures = Source.find_by!(title: "Planar Adventures", abbreviation: "PA", code: "PZO1141")
inner_sea_world_guide = Source.find_by!(title: "Pathfinder Campaign Setting: Inner Sea World Guide", abbreviation: "PCB: ISWG", code: "PZO9226")
inner_sea_bestiary = Source.find_by!(title: "Pathfinder Campaign Setting: Inner Sea Bestiary", abbreviation: "PCB: ISB", code: "PZO9251")
harrow_handbook = Source.find_by!(title: "Pathfinder Player Companion: The Harrow Handbook", abbreviation: "PPC: HH", code: "PZO9446")
custom = Source.find_by!(title: "Custom", abbreviation: "Custom", code: nil)


# //////////////////////////////////////////////////
# <-*-*-----*-*-*- Other References -*-*-*-----*-*->
# //////////////////////////////////////////////////

cr = Skillset.find_by!(name: "Core Rulebook")
dmc = Skillset.find_by!(name: "DMCustom")
ravnica_custom = Skillset.find_by!(name: "Ravnica Custom")

sorcerer = Klass.create!(name: "Sorcerer", hit_die: 6, skill_ranks: 2, fortitude: 0.34, reflex: 0.34, will: 0.5, img_url: "https://i.pinimg.com/originals/77/64/5e/77645e87b1f62b3c9e1d3f612fa5e679.jpg", starting_wealth: "2d6 × 10 gp (average 70 gp.) In addition, each character begins play with an outfit worth 10 gp or less.", source_id: core_rulebook.id, description: "Scions of innately magical bloodlines, the chosen of deities, the spawn of monsters, pawns of fate and destiny, or simply flukes of fickle magic, sorcerers look within themselves for arcane prowess and draw forth might few mortals can imagine. Emboldened by lives ever threatening to be consumed by their innate powers, these magic-touched souls endlessly indulge in and refine their mysterious abilities, gradually learning how to harness their birthright and coax forth ever greater arcane feats. Just as varied as these innately powerful spellcasters’ abilities and inspirations are the ways in which they choose to utilize their gifts. While some seek to control their abilities through meditation and discipline, becoming masters of their fantastic birthright, others give in to their magic, letting it rule their lives with often explosive results. Regardless, sorcerers live and breathe that which other spellcasters devote their lives to mastering, and for them magic is more than a boon or a field of study; it is life itself.

Role: Sorcerers excel at casting a selection of favored spells frequently, making them powerful battle mages. As they become familiar with a specific and ever-widening set of spells, sorcerers often discover new and versatile ways of making use of magics other spellcasters might overlook. Their bloodlines also grant them additional abilities, assuring that no two sorcerers are ever quite alike.

Alignment: Any")

ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: cr.id, skill_id: Skill.find_by!(name: "Appraise").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: cr.id, skill_id: Skill.find_by!(name: "Bluff").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: cr.id, skill_id: Skill.find_by!(name: "Craft").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: cr.id, skill_id: Skill.find_by!(name: "Fly").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: cr.id, skill_id: Skill.find_by!(name: "Intimidate").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: cr.id, skill_id: Skill.find_by!(name: "Knowledge (arcana)").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: cr.id, skill_id: Skill.find_by!(name: "Knowledge").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: cr.id, skill_id: Skill.find_by!(name: "Profession").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: cr.id, skill_id: Skill.find_by!(name: "Spellcraft").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: cr.id, skill_id: Skill.find_by!(name: "Use Magic Device").id)

ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: ravnica_custom.id, skill_id: Skill.find_by!(name: "Bluff").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: ravnica_custom.id, skill_id: Skill.find_by!(name: "Craft").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: ravnica_custom.id, skill_id: Skill.find_by!(name: "Intimidate").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: ravnica_custom.id, skill_id: Skill.find_by!(name: "Knowledge").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: ravnica_custom.id, skill_id: Skill.find_by!(name: "Profession").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: ravnica_custom.id, skill_id: Skill.find_by!(name: "Religion").id)
ClassSkillsetSkill.create!(klass_id: sorcerer.id, skillset_id: ravnica_custom.id, skill_id: Skill.find_by!(name: "Spellcraft", untrained: true).id)

# /////////////////////////////////////////////////////
# <-*-*-----*-*-*- Base Class Features!-*-*-*-----*-*->
# /////////////////////////////////////////////////////

sorcerer1 = KlassFeature.create!(klass_id: sorcerer.id, name: "Weapon and Armor Proficiency", description: "Sorcerers are proficient with all simple weapons. They are not proficient with any type of armor or shield. Armor interferes with a sorcerer’s gestures, which can cause her spells with somatic components to fail.")
  FeatureLevel.create!(klass_feature_id: sorcerer1.id, level: 1, table_description: "")
  sorcerer1_feature = Feature.create!()
    KlassFeatureFeature.create!(klass_feature_id: sorcerer1.id, feature_id: sorcerer1_feature.id)
    FeatureWeaponProficiency.create!(feature_id: sorcerer1_feature.id, proficiency_group: "Simple")

sorcerer2 = KlassFeature.create!(klass_id: sorcerer.id, name: "Spells", description: "A sorcerer casts arcane spells drawn primarily from the sorcerer/wizard spell list. She can cast any spell she knows without preparing it ahead of time. To learn or cast a spell, a sorcerer must have a Charisma score equal to at least 10 + the spell level. The Difficulty Class for a saving throw against a sorcerer’s spell is 10 + the spell level + the sorcerer’s Charisma modifier.

Like other spellcasters, a sorcerer can cast only a certain number of spells of each spell level per day. Her base daily spell allotment is given on Table: Sorcerer. In addition, she receives bonus spells per day if she has a high Charisma score (see Table: Ability Modifiers and Bonus Spells).

A sorcerer’s selection of spells is extremely limited. A sorcerer begins play knowing four 0-level spells and two 1st-level spells of her choice. At each new sorcerer level, she gains one or more new spells, as indicated on Table: Sorcerer Spells Known. (Unlike spells per day, the number of spells a sorcerer knows is not affected by her Charisma score; the numbers on Table: Sorcerer Spells Known are fixed.) These new spells can be common spells chosen from the sorcerer/wizard spell list, or they can be unusual spells that the sorcerer has gained some understanding of through study.

Upon reaching 4th level, and at every even-numbered sorcerer level after that (6th, 8th, and so on), a sorcerer can choose to learn a new spell in place of one she already knows. In effect, the sorcerer loses the old spell in exchange for the new one. The new spell’s level must be the same as that of the spell being exchanged. A sorcerer may swap only a single spell at any given level, and must choose whether or not to swap the spell at the same time that she gains new spells known for the level.

Unlike a wizard or a cleric a sorcerer need not prepare her spells in advance. She can cast any spell she knows at any time, assuming she has not yet used up her spells per day for that spell level.")
  FeatureLevel.create!(klass_feature_id: sorcerer2.id, level: 1, table_description: "")
  wizard_spell_list = SpellList.find_or_create_by!(name: "Wizard Spells List")
  sorcerer2_feature = Feature.create!()
    KlassFeatureFeature.create!(feature_id: sorcerer2_feature.id, klass_feature_id: sorcerer2.id)
    sorcerer_spellcasting = FeatureSpellcasting.create!(feature_id: sorcerer2_feature.id, ability_score: "charisma", prepare_spells: false, expend_prepared_spells: false, infinite_zero_level: true, known_spell_list: true, apply_metamagic_when_casting: true, apply_metamagic_when_preparing: false, type_of_magic: "Arcane", caster_level_penalty: 0, spell_list_id: wizard_spell_list.id)

    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 1, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 2, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 3, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 4, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 5, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 6, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 7, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 8, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 9, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 10, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 11, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 12, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 13, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 14, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 15, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 16, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 17, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 18, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 19, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 1, klass_level: 20, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 4, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 5, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 6, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 7, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 8, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 9, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 10, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 11, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 12, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 13, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 14, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 15, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 16, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 17, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 18, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 19, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 2, klass_level: 20, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 6, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 7, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 8, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 9, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 10, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 11, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 12, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 13, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 14, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 15, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 16, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 17, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 18, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 19, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 3, klass_level: 20, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 8, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 9, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 10, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 11, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 12, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 13, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 14, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 15, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 16, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 17, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 18, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 19, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 4, klass_level: 20, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 5, klass_level: 10, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 5, klass_level: 11, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 5, klass_level: 12, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 5, klass_level: 13, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 5, klass_level: 14, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 5, klass_level: 15, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 5, klass_level: 16, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 5, klass_level: 17, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 5, klass_level: 18, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 5, klass_level: 19, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 5, klass_level: 20, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 6, klass_level: 12, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 6, klass_level: 13, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 6, klass_level: 14, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 6, klass_level: 15, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 6, klass_level: 16, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 6, klass_level: 17, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 6, klass_level: 18, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 6, klass_level: 19, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 6, klass_level: 20, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 7, klass_level: 14, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 7, klass_level: 15, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 7, klass_level: 16, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 7, klass_level: 17, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 7, klass_level: 18, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 7, klass_level: 19, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 7, klass_level: 20, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 8, klass_level: 16, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 8, klass_level: 17, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 8, klass_level: 18, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 8, klass_level: 19, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 8, klass_level: 20, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 9, klass_level: 18, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 9, klass_level: 19, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    SpellsPerDayPerLevel.create!(spell_level: 9, klass_level: 20, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)

    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 1, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 2, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 3, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 4, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 5, spells: 6, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 6, spells: 7, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 7, spells: 7, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 8, spells: 8, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 9, spells: 8, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 10, spells: 9, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 11, spells: 9, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 12, spells: 9, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 13, spells: 9, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 14, spells: 9, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 15, spells: 9, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 16, spells: 9, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 17, spells: 9, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 18, spells: 9, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 19, spells: 9, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 0, klass_level: 20, spells: 9, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 1, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 2, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 3, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 4, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 5, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 6, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 7, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 8, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 9, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 10, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 11, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 12, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 13, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 14, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 15, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 16, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 17, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 18, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 19, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 1, klass_level: 20, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 4, spells: 1, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 5, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 6, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 7, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 8, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 9, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 10, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 11, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 12, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 13, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 14, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 15, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 16, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 17, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 18, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 19, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 2, klass_level: 20, spells: 5, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 6, spells: 1, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 7, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 8, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 9, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 10, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 11, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 12, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 13, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 14, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 15, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 16, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 17, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 18, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 19, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 3, klass_level: 20, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 8, spells: 1, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 9, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 10, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 11, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 12, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 13, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 14, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 15, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 16, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 17, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 18, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 19, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 4, klass_level: 20, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 5, klass_level: 10, spells: 1, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 5, klass_level: 11, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 5, klass_level: 12, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 5, klass_level: 13, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 5, klass_level: 14, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 5, klass_level: 15, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 5, klass_level: 16, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 5, klass_level: 17, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 5, klass_level: 18, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 5, klass_level: 19, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 5, klass_level: 20, spells: 4, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 6, klass_level: 12, spells: 1, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 6, klass_level: 13, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 6, klass_level: 14, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 6, klass_level: 15, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 6, klass_level: 16, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 6, klass_level: 17, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 6, klass_level: 18, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 6, klass_level: 19, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 6, klass_level: 20, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 7, klass_level: 14, spells: 1, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 7, klass_level: 15, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 7, klass_level: 16, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 7, klass_level: 17, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 7, klass_level: 18, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 7, klass_level: 19, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 7, klass_level: 20, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 8, klass_level: 16, spells: 1, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 8, klass_level: 17, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 8, klass_level: 18, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 8, klass_level: 19, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 8, klass_level: 20, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 9, klass_level: 18, spells: 1, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 9, klass_level: 19, spells: 2, feature_spellcasting_id: sorcerer_spellcasting.id)
    KnownSpellsPerLevel.create!(spell_level: 9, klass_level: 20, spells: 3, feature_spellcasting_id: sorcerer_spellcasting.id)

sorcerer3 = KlassFeature.create!(klass_id: sorcerer.id, name: "Bloodline", description: "Each sorcerer has a source of magic somewhere in her heritage that grants her spells, bonus feats, an additional class skill, and other special abilities. This source can represent a blood relation or an extreme event involving a creature somewhere in the family’s past. For example, a sorcerer might have a dragon as a distant relative or her grandfather might have signed a terrible contract with a devil. Regardless of the source, this influence manifests in a number of ways as the sorcerer gains levels. A sorcerer must pick one bloodline upon taking her first level of sorcerer. Once made, this choice cannot be changed.

At 3rd level, and every two levels thereafter, a sorcerer learns an additional spell, derived from her bloodline. These spells are in addition to the number of spells given on Table: Sorcerer Spells Known. These spells cannot be exchanged for different spells at higher levels.

At 7th level, and every six levels thereafter, a sorcerer receives one bonus feat, chosen from a list specific to each bloodline. The sorcerer must meet the prerequisites for these bonus feats.

Filled with magical power that screams for release, sorcery is not so much a calling as a blessing—or a curse. For some sorcerers, this arcane birthright manifests in subtle and carefully controlled ways, assisting in their manipulation of others or the pursuit of lofty goals. For others, it is wild and unpredictable, the primal and explosive lashing out of a power greater than themselves. Presented below are a number of bloodlines representing the mysterious origin of your sorcerer’s abilities.

The following bloodlines represent only some of the possible sources of power that a sorcerer can draw upon. Unless otherwise noted, most sorcerers are assumed to have the arcane bloodline.", specialization: true, choice_amount: 1)
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 1, table_description: "Bloodline Power")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 3, table_description: "Bloodline Power")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 9, table_description: "Bloodline Power")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 15, table_description: "Bloodline Power")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 20, table_description: "Bloodline Power")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 3, table_description: "Bloodline Spell")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 5, table_description: "Bloodline Spell")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 7, table_description: "Bloodline Spell")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 9, table_description: "Bloodline Spell")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 11, table_description: "Bloodline Spell")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 13, table_description: "Bloodline Spell")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 15, table_description: "Bloodline Spell")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 17, table_description: "Bloodline Spell")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 19, table_description: "Bloodline Spell")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 7, table_description: "Bloodline Feat")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 13, table_description: "Bloodline Feat")
  FeatureLevel.create!(klass_feature_id: sorcerer3.id, level: 19, table_description: "Bloodline Feat")

sorcerer4 = KlassFeature.create!(klass_id: sorcerer.id, name: "Cantrips", description: "Sorcerers learn a number of cantrips, or 0-level spells, as noted on Table: Sorcerer Spells Known under “Spells Known.” These spells are cast like any other spell, but they do not consume any slots and may be used again.")
  FeatureLevel.create!(klass_feature_id: sorcerer4.id, level: 1, table_description: "Cantrips")

sorcerer5 = KlassFeature.create!(klass_id: sorcerer.id, name: "Eschew Materials", description: "A sorcerer gains Eschew Materials as a bonus feat at 1st level.")
  FeatureLevel.create!(klass_feature_id: sorcerer5.id, level: 1, table_description: "Eschew Materials")
  sorcerer5_feature = Feature.create!()
    KlassFeatureFeature.create!(klass_feature_id: sorcerer5.id, feature_id: sorcerer5_feature.id)
    FeatureBonusFeat.create!(feature_id: sorcerer5_feature.id, feat_id: Feat.find_by!(name: "Eschew Materials").id, player_choice: false)

print "Sorcerer Features Created! \r"

# //////////////////////////////////////////////////
# <-*-*-----*-*-*- Class Archetypes!-*-*-*-----*-*->
# //////////////////////////////////////////////////



puts "Sorcerer Created!"
